### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by adamnovak** [glennhickey/sg2vg#1]
I tried this:

```
./ga2vg http://ec2-54-149-188-244.us-west-2.compute.amazonaws.com/debruijn-sma-k31/v0.6.g | less

```

And I got this:

```
Downloading References... (4329 references retrieved)
Downloading Sequences...terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: POST request for Sequences returned {"errorCode": 2023404236, "message": "Request '{u'pageToken': None, u'variantSetId': None, u'referenceSetId': None, u'pageSize': 2147483647}' is not a valid instance of <class 'ga4gh._protocol_definitions.SearchSequencesRequest'>"}

```

Looks like it's sending bad requests to the server.

**Comment by glennhickey** [comment]
please hold off using sg2vg for now.  it's not finished, and there are
graph server issues that need to be resolved (and hence the protocol is in
a state of flux).

**Comment by glennhickey** [comment]
ok, sg2vg's using the new protocol and passing some basic unit tests.  i'm
going to look at some integration tests now.

the server still bombs out for anything bigger than brca2, so use at your
own risk!

**Comment by adamnovak** [comment]
OK, it seems to work now. Thanks!
