### ISSUE TITLE
VG JSON output is semantically invalid

### ISSUE THREAD

**Issue by adamnovak** [glennhickey/sg2vg#2]
There are a few issues with the JSON output that make it semantically invalid for vg.

Here's an example of some edges that sg2vg is making (from `sg2vg http://ec2-54-149-188-244.us-west-2.compute.amazonaws.com/camel-brca2/v0.6.g | jq ".edge" | less`)

```
 {
    "from": 0,
    "to": 1,
    "from_start": false,
    "to_end": false
  },
  {
    "from": 1,
    "to": 0,
    "from_start": true,
    "to_end": true
  },
  {
    "from": 0,
    "to": 197,
    "from_start": false,
    "to_end": false
  },
  {
    "from": 197,
    "to": 0,
    "from_start": true,
    "to_end": true
  },
  {
    "from": 1,
    "to": 2,
    "from_start": true,
    "to_end": false
  },
  {
    "from": 2,
    "to": 1,
    "from_start": true,
    "to_end": false
  },
  {
    "from": 2,
    "to": 197,
    "from_start": true,
    "to_end": false
  },
  {
    "from": 197,
    "to": 2,
    "from_start": true,
    "to_end": false
  },
```

First, it looks like the node ID 0 is being used. VG reserves 0 in a variety of places for nonexistent nodes; the lowest valid node ID is 1. This ought to be caught as an error by VG on JSON import, but it isn't.

Second, it looks like edges are being articulated in both directions. We have an edge from the start of 1 to the start of 2, and an edge from the start of 2 to the start of 1. This isn't invalid per se, but it is unnecessary. VG interprets those edges as meaning exactly the same thing (since they connect the same ends of the same nodes, and would be stored in the same places in its internal indices) so once it loads the first one, it drops the second. There ought to be a warning in the VG JSON importer about this, too.

Finally, some of the nodes meant to represent SNP alternatives are attached only by one side. For example, look at node 197. There's an edge from the end of node 0 to the start of node 197, a duplicate edge from the start of 197 to the end of 0, an edge from the start of 2 to the start of 197, and a duplicate edge from the start of 197 to the start of 2. Those are all the edges that attach to node 197, and all of them attach to its start. It seems like there should be an edge connecting the *end* of 197 to the start of 2, instead of the *start* of 197.

Perhaps `from_start` and `to_end` aren't being used properly? Nodes have two sides, start and end. A default, normal edge has `from_start` and `to_end` set to false, and connects the end of the `from` node to the start of the `to` node. If `from_start` is true, the edge involves the start of the `from` node instead of the end, and if `to_end` is true, the edge involves the end of the `to` node instead of the start. Note that inverting `from_start` and `to_end` and swapping the `from` and `to` nodes produces a semantically identical edge; if both are specified, VG remembers only one.

There's also the issue of VG assuming in some places that a range of nodes is a good approximation for a region of the graph, which is incorrect for these graphs (where nodes 197 and 1 are alternatives for the same SNP), but that's more a shortcoming of VG that needs to be fixed.

**Comment by adamnovak** [comment]
With the output as it is, the graph more or less correctly describes one path, but all the variants from it are wrong. So read alignment works, but it isn't very good.

If you want to see what VG thinks of your graph, use `vg view -Jv` to make JSON into VG, and `vg view -j` to make VG into JSON again.

**Comment by glennhickey** [comment]
Thanks, Adam.

Didn't know about the 1-based id's (though I should have by now).  That
will be easy to fix.

I was working under the impression that VG edges were directed.  So I was
actually going out of my way to put the two versions! (something that was
on my list to verify but got lost dealing with all the server issues).

I see your point about the 197 SNP.  I must be screwing up the
from_start/to_end flags consistently in both code and tests, somehow.  Will
get on all these issues right away.

**Comment by glennhickey** [comment]
Hmm, looks like the start/end flags problem was just in writing the json
strings, which i never bothered writing a unit test for...

Anyway, these three issues should be resolved in the latest version.  But
I'm a bit worried that my JSON paths may also make wrong assumptions.  I'll
go back and check, but if you're using them please let me know if you see
anything!

For the id values being meaningful (again, total news to me), I can look at
running some kind of sort.  But it seems pretty hokey as a concept.

Thanks again!
-Glenn

**Comment by adamnovak** [comment]
It is a bit of a bad heuristic. It's one of the things I would like to change, or at least rely on only for speed instead of for correctness.

I will test this new version and see how it works.

**Comment by adamnovak** [comment]
This all works now.

It does seem to have a tendency to use from_start and to_end at the same time, when you could just write the edge the other direction with both false, but that's still correct so I'm going to close this.

**Comment by glennhickey** [comment]
Yeah, I think I'm storing side graph edges such that they always start at
the node with the lowest id.  If the double-false edges ever become a
problem, it should be pretty simple to remove them from the vg output...
