### ISSUE TITLE
Clean build on Mac OS X gives -> libc++abi.dylib: terminating with uncaught exception

### ISSUE THREAD

**Issue by JervenBolleman** [glennhickey/sg2vg#7]
mac os x 10.10.5 (14F27) 
with
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

```
make
make test
```
Trying to look at the help page.
```
./sg2vg -h
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Version not detected at end of URL
Abort trap: 6
```

**Comment by glennhickey** [comment]
Seems -h doesn't work for whatever reason.  I'll fix this shortly but
please just run sg2vg without any arguments to get the help menu.  Sorry
about that!

**Comment by glennhickey** [comment]
Fixed.
